baseURL = 'https://ashwini.dev/'
languageCode = 'en-us'
title = "Ashwini Manoj's blog"
theme = "PaperMod"

DefaultContentLanguage = "en"

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "/posts"
name = "Posts"
weight = 1

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[taxonomies]
   tag = "tags"

[params]
	social = true
